name: 打包应用上传百度云

on:
  push:
    branches:
      - master

jobs:
  build:
    # 指定job任务运行所需要的虚拟机字段 (必填)
    runs-on: ubuntu-latest
    steps:
      -  name: 拉取代码
         uses: actions/checkout@v2
      # 安装Node
      -  name: 安装Node
         uses: actions/setup-node@v3
         with:
          node-version: 18
          cache: npm
      # 安装依赖
      -  name: 安装依赖
         run: npm install
      # 打包应用
      -  name: 打包应用
         run: npm run docs:build
      # 部署应用
      -  name: 上传百度云
         uses: easingthemes/ssh-deploy@v2.1.5
         env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          # scp参数
          ARGS: "-avzr --delete"
          SOURCE: "dist"
          # 服务器ip
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          # 用户
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          # 目标地址
          TARGET: ${{ secrets.TARGET }}
      # 部署Github
      -  name: 部署Github
         uses: JamesIves/github-pages-deploy-action@v4.2.5
         with:
          branch: gh-pages
          folder: dist
          clean: true
